# Generated by Django 3.1.3 on 2021-04-12 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
    ]
