# Generated by Django 3.1.3 on 2021-04-14 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_delete_productvariation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
