# Generated by Django 3.1.3 on 2021-04-14 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='ProductImage',
        ),
    ]
